
__all__ = [
    "UsernameNotFound",
    "InvalidPassword",
    "UsernameAlreadyExists",
    "BadAuthToken",
    "InvalidStatusValue",
    "FaildToInitChannels",
    "NotAnAdminOrServerOwner",
    "ChannelNameAlreadyExists",
    "ChannelNotFound",
    "FaildToRemoveUserFromChannelUserIsAdmin",
    "ExceededMaxMessagesPerPage",
    "MessageIsTooLong",
    "MessageNotFound",
    "UserNotFound",
    "FileNotFound",
    "UnsupportedFileType",
    "IPSecurityError",
    "ServerError"
]

# Signin exceptions
class UsernameNotFound(Exception): ...
class InvalidPassword(Exception): ...

# Signup exceptions
class UsernameAlreadyExists(Exception): ...

# Auth token exceptions
class BadAuthToken(Exception): ...

# Update user profile
class InvalidStatusValue(Exception): ...

# Initialize the Channels
class FaildToInitChannels(Exception): ...

# Not an admin or server owner exception
class NotAnAdminOrServerOwner(Exception): ...

# Channels exceptions
class ChannelNameAlreadyExists(Exception): ...
class ChannelNotFound(Exception): ...
class FaildToRemoveUserFromChannelUserIsAdmin(Exception): ...
class ExceededMaxMessagesPerPage(Exception): ...
class MessageIsTooLong(Exception): ...
class MessageNotFound(Exception): ...

class UserNotFound(Exception): ...

# File operations exceptions
class FileNotFound(Exception): ...
class UnsupportedFileType(Exception): ...

# Admin operations exceptions
class IPSecurityError(Exception): ...
class ServerError(Exception): ...
