name: Sphinx docs

on:
  push:
    branches:
      - main
      - docs

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10.*"    # Python version to build the html sphinx documentation
          environment-file: devtools/cond-envs/docs_env.yaml    # Path to the documentation conda environment
          miniconda-version: "latest"
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
        with:
          branch: main
          dir_docs: docs
          sphinx-apidoc-opts: '--separate -o . ../'
          sphinx-apidoc-exclude: '../*setup* ../*.ipynb'
          sphinx-opts: ''